### PR TITLE
Add gitginore setting items for IntelliJ IDEA

### PR DESCRIPTION
**Pull request by LinuxSuRen**

### CODE REVIEW

**Review by dominiquebrice — APPROVED** [review]

**Comment by LinuxSuRen** [comment]
hi @dominiquebrice, Thanks for giving me a quick review. I'd like to use this plugin in my business. There're a couple of things I'd like to improve. I want to get all Jenkins node labels via API. So I'm going to create another PR against this feature.

**Comment by dominiquebrice** [comment]
hi @LinuxSuRen, it's unlikely that I will have the time to merge more complex PRs. I haven't worked on this plugin for a few years now, and I'm thinking about marking the plugin for adoption. I will follow the process described on this page (https://www.jenkins.io/doc/developer/plugin-governance/adopt-a-plugin/) in the next few weeks.

**Comment by LinuxSuRen** [comment]
I'm also a maintainer of a few plugins. Consider that I'd like to start an adaption process of this plugin. Of course, I need your approval.

**Comment by LinuxSuRen** [comment]
hi @dominiquebrice , I started an adoption process [here](https://groups.google.com/g/jenkinsci-dev/c/AJHNwf3iVO8/m/7_0InOcsAAAJ). We can push it forward if you're ok with that.

**Pull request merged**
